### ISSUE TITLE
Error running Python program from code_playground: ModuleNotFoundError: No module named 'matplotlib.pyplot'; 'matplotlib' is not a package

### ISSUE THREAD

**Issue by mnyon-grandkru** [trystant/knowledgebase#119]
```
➜  code_playground python matplotlib.py
Traceback (most recent call last):
  File "/home/mnyon/code_playground/matplotlib.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/home/mnyon/code_playground/matplotlib.py", line 1, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib.pyplot'; 'matplotlib' is not a package
```

matplotlib is installed:
```
➜  code_playground python3 -m pip install -U matplotlib
Requirement already satisfied: matplotlib in /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.6_1/lib/python3.11/site-packages (3.8.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.6_1/lib/python3.11/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.6_1/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.6_1/lib/python3.11/site-packages (from matplotlib) (4.50.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.6_1/lib/python3.11/site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy<2,>=1.21 in /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.6_1/lib/python3.11/site-packages (from matplotlib) (1.26.1)
Requirement already satisfied: packaging>=20.0 in /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.6_1/lib/python3.11/site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.6_1/lib/python3.11/site-packages (from matplotlib) (9.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.6_1/lib/python3.11/site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.6_1/lib/python3.11/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.6_1/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
```

and the import is simply the following within the code itself:
```
import matplotlib.pyplot as plt
```

I'm not sure why this is happening, but I'm preserving this so I solve this before I need to use matplotlib for anything.

**Comment by mnyon-grandkru** [comment]
I haven't needed this, so I'll close it for now.
