### ISSUE TITLE
Error importing images from Flickr to P Stash

### ISSUE THREAD

**Issue by trystant** [trystant/knowledgebase#35]
When using the [Flickr2Piwigo](http://piwigo.org/ext/extension_view.php?eid=612) plugin on media.grandkru.com, I ran into the following error:

```
Fatal error: Uncaught Error: Call to undefined function OAuth\Common\Http\Client\curl_init() in /var/www/html/piwigo/plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/CurlClient.php:86 Stack trace: #0 /var/www/html/piwigo/plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/OAuth1/Service/Flickr.php(98): OAuth\Common\Http\Client\CurlClient->retrieveResponse(Object(OAuth\Common\Http\Uri\Uri), Array, Array, 'POST') #1 /var/www/html/piwigo/plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/OAuth1/Service/Flickr.php(124): OAuth\OAuth1\Service\Flickr->request('flickr.test.log...', 'POST', Array, Array) #2 /var/www/html/piwigo/plugins/flickr2piwigo/vendor/samwilson/phpflickr/src/PhpFlickr.php(347): OAuth\OAuth1\Service\Flickr->requestJson('flickr.test.log...', 'POST', Array) #3 /var/www/html/piwigo/plugins/flickr2piwigo/vendor/samwilson/phpflickr/src/TestApi.php(31): Samwilson\PhpFlickr\PhpFlickr->request('flickr.test.log...', Array, true) #4 /var/www/html/piwigo/plugins/flickr2piwigo/admin/impo in /var/www/html/piwigo/plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/CurlClient.php on line 86
```

**Comment by trystant** [comment]
It looks like adding php-curl support can help. i just need to get access & install it.

**Comment by trystant** [comment]
I'm going to put this on hold because I need to resurrect the P Stash
