### ISSUE TITLE
TypeError: Todo.insertMany is not a function

### ISSUE THREAD

**Issue by trystant** [trystant/knowledgebase#41]
This is occurring in a [Glitch](https://glitch.com/edit/#!/pretty-humidity).
```
  TypeError: Todo.insertMany is not a function
  at mongoose.connection.dropDatabase.then (test/server.test.js:32:24)
  at <anonymous>
  at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by trystant** [comment]
This turned out to be because of an assignment wasn't destructured. Destructuring the constant solved the problem.
