### ISSUE TITLE
Running into fork errors when running rake task

### ISSUE THREAD

**Issue by trystant** [trystant/knowledgebase#45]
Running the following Rake tasks results in these errors on my development environment for a client:

```
 Teacher manages reports Teacher download share report in xlsx format, expect to find student name
      Failure/Error: window = Capybara.current_session.driver.browser.manage.window

      Errno::ENOMEM:
        Cannot allocate memory - fork(2)
   # /usr/local/rvm/gems/ruby-2.4.1@client/gems/childprocess-0.9.0/lib/childprocess/unix/fork_exec_process.rb:20:in `fork'
      # /usr/local/rvm/gems/ruby-2.4.1@client/gems/childprocess-0.9.0/lib/childprocess/unix/fork_exec_process.rb:20:in `launch_process'
      # /usr/local/rvm/gems/ruby-2.4.1@client/gems/childprocess-0.9.0/lib/childprocess/abstract_process.rb:81:in `start'
      # /usr/local/rvm/gems/ruby-2.4.1@client/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/firefox/service.rb:45:in `start_process'
      # /usr/local/rvm/gems/ruby-2.4.1@client/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/service.rb:71:in `block in start'
      # /usr/local/rvm/gems/ruby-2.4.1@client/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/socket_lock.rb:39:in `locked'
      # /usr/local/rvm/gems/ruby-2.4.1@client/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/service.rb:69:in `start'
      # /usr/local/rvm/gems/ruby-2.4.1@client/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/firefox/marionette/driver.rb:42:in `initialize'
      # /usr/local/rvm/gems/ruby-2.4.1@client/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/firefox/driver.rb:31:in `new'
      # /usr/local/rvm/gems/ruby-2.4.1@client/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/firefox/driver.rb:31:in `new'
      # /usr/local/rvm/gems/ruby-2.4.1@client/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/driver.rb:52:in `for'
      # /usr/local/rvm/gems/ruby-2.4.1@client/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver.rb:86:in `for'
```

**Comment by trystant** [comment]
I am closing this since work on the project has been stopped
