### ISSUE TITLE
Errno::ECONNREFUSED in ClientController#index

### ISSUE THREAD

**Issue by trystant** [trystant/knowledgebase#65]
I'm getting an error message when attempting to view my local environment. The specific error message is: 
`Failed to open TCP connection to client.localhost:443 (Connection refused - connect(2) for "client.localhost" port 443)

```
app/lib/*_mixin.rb:33:in `enrollments'
app/lib/*_mixin.rb:20:in `current_user_from_session_jwt'
app/lib/*_mixin.rb:15:in `current_user'
app/lib/*_mixin.rb:61:in `load_current_user'
app/middleware/log_pings.rb:13:in `call'
app/middleware/*_ware/choice.rb:21:in `call'
```

**Comment by trystant** [comment]
It turns out the reason for this issue had to do with multiple specs using the same `DummyController` class in the codebase. Once one of the controller classes was changed, this error was resolved.
